name: Veracode CLI

on:
  workflow_dispatch:

jobs:

  veracode-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Download Veracode CLI
      with:
        args: -fsS https://tools.veracode.com/veracode-cli/install | sh
    - name: Test Instalation
      run: ./veracode --version
      env:
        VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
        VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
