
name: Veracode DAST

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Build JSON file
        run: |
          touch input.json
          echo "
            {
              "name": "Name-of-Your-Dynamic-Analysis",
              "scans": [
                {
                  "scan_config_request": {
                    "target_url": {
                      "url": "http://www.example.com"
                    }
                  }
                }
              ],
              "schedule": {
                "duration": {
                  "length": 1,
                  "unit": "DAY"
                },
                "scheduled": true,
                "now": true
              }
            } "
      - name: Create DAST Scan
        run:
          python --version
          python -m pip install --upgrade pip wheel
          python -m pip install httpie
          pip install veracode-api-signing
          Get-Content input.json | http --auth-type=veracode_hmac POST "https://api.veracode.com/was/configservice/v1/analyses?run_verification=true"
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
