name: Mitigation Copier

on: workflow_dispatch

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run:
        - git clone https://github.com/tjarrettveracode/veracode-mitigation-copier
        - cd veracode-mitigation-copier
        - pip install -r requirements.txt
        - ls
