name: Mitigation Copier

on: workflow_dispatch

jobs:
  run_commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        git clone https://github.com/tjarrettveracode/veracode-mitigation-copier
        cd veracode-mitigation-copier
        pip install -r requirements.txt

    - name: Export Credentials
      run: |
        export VERACODE_API_KEY_ID=${{secrets.VERACODE_API_ID}}
        export VERACODE_API_KEY_SECRET=${{secrets.VERACODE_API_KEY}}
        cd veracode-mitigation-copier
        python MitigationCopier.py --fromapp bef68596-41a2-4a8a-a9ad-9d55ff570aaa --toapp e962ed0e-c251-4136-92b0-ab66e37eca56


      
