name: Mitigation Copier

on: workflow_dispatch

jobs:
  run_commands:
    runs-on: ubuntu-latest  # You can choose a different OS if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the Python version you need

    - name: Install dependencies
      run: |
        git clone https://github.com/tjarrettveracode/veracode-mitigation-copier
        cd veracode-mitigation-copier
        pip install -r requirements.txt

    - name: List files
      run: ls
      
    - name: Create credentials file and store secrets
      run: |
        echo "VERACODE_API_KEY_ID= ${{secrets.VERACODE_API_ID}}" > credentials
        echo "VERACODE_API_KEY_SECRET= ${{secrets.VERACODE_API_KEY}}" >> credentials
        cat credentials  # Display the content of the file for verification

    - name: Mitigation Copier Command
      run: python MitigationCopier.py --fromapp abcdefgh-1234-abcd-1234-123456789012 --toapp 12345678-abcd-1234-abcd-abcdefghijkl

      #export VERACODE_API_KEY_ID=<YOUR_API_KEY_ID>
      #export VERACODE_API_KEY_SECRET=<YOUR_API_KEY_SECRET>
      #python MitigationCopier.py (arguments)
      
