name: Veracode Agent Based Scan

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      working-directory: app
      run: mvn -B package --file pom.xml

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Run Veracode SCA
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      uses: veracode/veracode-sca@v2.1.10
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        quick: false
        create-issues: false 
