
name: Veracode Agent Based Scan

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
  
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs an SCA agent-based scan in the local directory
    - name: Execute Software Composition Analysis
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: cd ./app curl -sSL https://download.sourceclear.com/ci.sh | sh
      
